# Generated by Django 3.2.4 on 2021-06-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbu',
            name='reach',
            field=models.JSONField(verbose_name='Охват'),
        ),
    ]
